name: Make QGIS Plugin Zip for Manual Installs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  buildpackage:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r $GITHUB_WORKSPACE/QGISAnimationWorkbench.zip animation_workbench
        working-directory: $GITHUB_WORKSPACE/QGISAnimationWorkbench
      - uses: actions/upload-artifact@v3
        with:
          name: QGISAnimationWorkbench
          working-directory: $GITHUB_WORKSPACE/QGISAnimationWorkbench
          path: animation_workbench
          
