name: Make QGIS Plugin Zip for Manual Installs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  buildpackage:
    name: Build Package
    runs-on: ubuntu-latest
    steps:

      - uses: actions/upload-artifact@v3
        with:
          name: QGISAnimationWorkbench
          path: /home/runner/work/QGISAnimationWorkbench/QGISAnimationWorkbench/animation_workbench
