name: Make QGIS Plugin Zip for Manual Installs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
  # Allow manually running in the actions tab
  workflow_dispatch:

jobs:
  buildpackage:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r /tmp/QGISAnimationWorkbench.zip animation_workbench
      - uses: actions/upload-artifact@v3
        with:
          name: QGISAnimationWorkbench
          path: /tmp/QGISAnimationWorkbench.zip
